name: Publish npm packages

on:
    push:
        branches:
            - main

jobs:
    publish:
        name: Build and publish npm packages with lerna
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  ref: 'main'

            - name: git config user
              run: |
                  git config user.email "designsystem@sparebank1.no"
                  git config user.name "sb1-designsystem"

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: 'https://registry.npmjs.com'

            - run: |
                  npm install
                  echo "$GITHUB_WORKSPACE/node_modules/.bin/" >> $GITHUB_PATH

            - name: lerna changed
              id: lerna-changed
              run: echo "::set-output name=count::$(lerna changed|wc -l)"

            - name: lerna publish to registry.npmjs.com
              if: ${{ steps.lerna-changed.outputs.count > 0 }}
              run: lerna publish --yes --create-release github
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_USER_TOKEN }}

            - name: Merge back changes to development branch
              if: ${{ steps.lerna-changed.outputs.count > 0 }}
              run: |
                  git checkout develop
                  git pull
                  git merge -X theirs --no-edit main
                  git push origin develop
                  git push --tags
